# Generated by Django 5.0.4 on 2024-08-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_message',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
