# Generated by Django 5.0.4 on 2024-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Likes'), (2, 'Follow'), (3, 'Message')]),
        ),
    ]
