# Generated by Django 5.0.4 on 2024-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save_post',
            field=models.ManyToManyField(blank=True, related_name='saved_post', to='core.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to='profile'),
        ),
    ]
