# Generated by Django 5.0.4 on 2024-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_save_post_post_favourite_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messagers',
            field=models.ManyToManyField(blank=True, related_name='messages', to='core.profile'),
        ),
    ]
