# Generated by Django 5.0.4 on 2024-08-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_messagers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='messagers',
            field=models.ManyToManyField(blank=True, to='core.profile'),
        ),
    ]
