# Generated by Django 5.0.4 on 2024-10-29 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='reset',
            field=models.UUIDField(default=uuid.UUID('efb47ec0-5336-4271-b506-7cdbc8f22c5a'), editable=False, unique=True),
        ),
    ]
